### ISSUE TITLE
Warning for every fields on pspp "Warning: v00001 listed in very long string record with width 0032, which requires only one segment"

### ISSUE THREAD

**Issue by nzalheart444** [tiamo/spss#56]
First of all thank you for this great library. It has been of great help to us.

We are using GNU PSPP 1.4.1. We get warning for all fields width. SPSS considers width greater than 255 to be long string record. But at the moment, every field is being listed in very long string record. 

![Selection_014](https://user-images.githubusercontent.com/49517081/102445121-daf64280-4052-11eb-9b5b-ed6c802fe310.png)

This is a code snippet from Sav/Writer.php around line 179. Apparently the Record\Variable::isVeryLong($var->width) is expected to return boolean value if we look at the implementation. Because of this every field is being marked as very long string.

    if (Record\Variable::isVeryLong($var->width) !== 0) {
         $this->info[Record\Info\VeryLongString::SUBTYPE][$shortName] = $var->width;
    }

I replace 0 with false and could get rid of the warnings. But when using width above 255, We get blank file on GNU PSPP. Because of this we are bound to use width below 255.

**Comment by lestcape** [comment]
I notice this https://github.com/tiamo/spss/blob/c5ce42cb6555ef2eeace76775789c9445af51ec6/src/Sav/Record/Data.php#L466 and this https://github.com/tiamo/spss/blob/c5ce42cb6555ef2eeace76775789c9445af51ec6/src/Sav/Record/Data.php#L379
and probably the correct is:
```php
$width = ($var->write[2] !== 0) ? $var->write[2] : $var->width;
```
As it's always set, because in the initialization is set as cero: https://github.com/tiamo/spss/blob/c5ce42cb6555ef2eeace76775789c9445af51ec6/src/Sav/Record/Variable.php#L65

Then in the writer this seem to be wrong too:
https://github.com/tiamo/spss/blob/c5ce42cb6555ef2eeace76775789c9445af51ec6/src/Sav/Writer.php#L118-L129

Probably the correct code should be:
```php
$variable->print = [
    0,
    $var->format,
    $var->width !== 0 ? min($var->width, 255) : 8,
    $var->decimals,
];
$variable->write = [
     0,
     $var->format,
     $var->width !== 0 ? min($var->width, 255) : 8,
     $var->decimals,
];
```
Also the description of seem to be in a different order of how they are set here:
https://github.com/tiamo/spss/blob/c5ce42cb6555ef2eeace76775789c9445af51ec6/src/Sav/Record/Variable.php#L51-L65

So, i think all this should be fixed and then see if the test [LongStringTest](https://github.com/tiamo/spss/blob/c5ce42cb6555ef2eeace76775789c9445af51ec6/tests/LongStringTest.php) pass. @nzalheart444 can you add all that changes and test again if that fixed the problem?

**Comment by lestcape** [comment]
If I replace 0 with false I get rid of the warnings, but also spss and pspp can read a file with a long a string data and just with that change also the LongString test pass. So, i have not an example to test the issue you mention is produced with pspp after the replace of 0 with false.

**Comment by lestcape** [comment]
@nzalheart444 https://github.com/tiamo/spss/pull/62 should fix this issue.
