### ISSUE TITLE
Does not allow # in names?

### ISSUE THREAD

**Issue by sinnbeck** [tiamo/spss#69]
I am trying to write a sav file, but it seems that this regex does not allow `#`? That should be valid character in spss names?

https://github.com/tiamo/spss/blob/master/src/Sav/Writer.php#L115C31-L115C67

From an existing .sav file
![image](https://github.com/tiamo/spss/assets/13980140/036d7114-6142-4546-8b0d-46cf48202f54)

**Comment by lestcape** [comment]
The $, #, and @ are special characters if they are written in a specific position, but they can also be used as part of the name if not. I think they are excluded here for simplicity. The reader must read it (otherwise we won't be able to read some files), but nothing forces the writer to allow it, since you can control how the file will be written. So I don't have a firm position on allowing the writer to use it or not. If you want that possibility to be included, please create a PR for that. If it doesn't affect anything else and the resulting file can be read, I don't see why it can't be merged.

**Comment by sinnbeck** [comment]
I will also suggest replacing `A-Za-z` with `\w` as that should allow any word character (eg. æøå from the danish alphabet)

**Comment by lestcape** [comment]
Yes is the same, if is tested and we can write special characters without a problem, i don't see why not. This is allowed by the sav file specification. Just take care top not allow the inclusion of $, # in the first position and follow the that rules you linked.
